### ISSUE TITLE
Small Error in "Handling Missing Data" Section

### ISSUE THREAD

**Issue by tsela** [tk3369/www.ahsmart.com#4]
Hi,

Great resource this DataFrames.jl cheat sheet. However, I noticed a small error in the "Handling Missing Data" section. Under both `allowmissing(df, :sibsp)` and `disallowmissing(df, :sibsp)` is the same text "Change column to allow missing data." I take it that under `disallowmissing(df, :sibsp)` the text should actually be "Change column to disallow missing data."

But apart from that, thanks for taking the time to put this up! I've been hoping to get my hands on such a cheat sheet for quite a while now!

**Comment by tk3369** [comment]
Thanks for the report.
