### ISSUE TITLE
Hope you will be able to do some documentation like this for other well-known packages

### ISSUE THREAD

**Issue by zsz00** [tk3369/www.ahsmart.com#7]
This style of documentation is very simple and perfect, Many people like it very much!!
Can you do the same style documentation  for other well-known packages??  such as Flux, MLJ, DifferentialEquations ...

**Comment by tk3369** [comment]
Thank you :-) Thanks for the suggestion but I'm not familiar with those packages. I can reconsider if I ever I dig deep into that part of the ecosystem in the future!
